version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8083:80
    depends_on:
      - app
    container_name: bailanysbar_nginx

  app:
    build:
      args:
        user: ubuntu
        uid: 1000
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    container_name: bailanysbar_app

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bailanysbar
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8301:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: bailanysbar_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: bailanysbar_phpmyadmin
    depends_on:
      - db
    ports:
      - 8302:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
